'''
Author: BOKTIAR AHMED BAPPY
Designation: Data Scientist
Date: 14/04/1022
Email: 1. boktiar@ineuron.ai  2. entbappy73@gmail.com
'''

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from desktop_exception_layer.exception import GenericException as GUIException
from desktop_config_layer.configuration import AssistantConfiguration


'''
WARNING!!!: Any manual changes made to this file will be hamrmful for your application.
Do not edit this file unless you know what you are doing.
'''


class Ui_iNeuronDesktopAssistant(object):

    def __init__(self):
        self.config = AssistantConfiguration()

    def setupUi(self, iNeuronDesktopAssistant):
        try:
            iNeuronDesktopAssistant.setObjectName("iNeuronDesktopAssistant")
            iNeuronDesktopAssistant.resize(1366, 720)
            self.centralwidget = QtWidgets.QWidget(iNeuronDesktopAssistant)
            self.centralwidget.setObjectName("centralwidget")
            self.BG1 = QtWidgets.QLabel(self.centralwidget)
            self.BG1.setGeometry(QtCore.QRect(-10, 0, 1381, 721))
            self.BG1.setText("")
            self.BG1.setPixmap(QtGui.QPixmap(self.config.BACKGROUND_IMAGE_DIR))  #BACKGROUND_IMAGE_DIR
            self.BG1.setScaledContents(True)
            self.BG1.setObjectName("BG1")
            self.initializing_gif = QtWidgets.QLabel(self.centralwidget)
            self.initializing_gif.setGeometry(QtCore.QRect(10, -20, 371, 151))
            self.initializing_gif.setText("")
            self.initializing_gif.setPixmap(QtGui.QPixmap(self.config.INITIALIZING_GIF_DIR))  #INITIALIZING_GIF_DIR
            self.initializing_gif.setScaledContents(False)
            self.initializing_gif.setObjectName("initializing_gif")
            self.prog_gif = QtWidgets.QLabel(self.centralwidget)
            self.prog_gif.setGeometry(QtCore.QRect(10, 100, 371, 211))
            self.prog_gif.setText("")
            self.prog_gif.setPixmap(QtGui.QPixmap(self.config.CODE_LEFT_GIF_DIR))  #CODE_LEFT_GIF_DIR
            self.prog_gif.setScaledContents(True)
            self.prog_gif.setObjectName("prog_gif")
            self.world_gif = QtWidgets.QLabel(self.centralwidget)
            self.world_gif.setGeometry(QtCore.QRect(-30, 300, 451, 341))
            self.world_gif.setText("")
            self.world_gif.setPixmap(QtGui.QPixmap(self.config.EARTH_GIF_DIR))   #EARTH_GIF_DIR
            self.world_gif.setScaledContents(True)
            self.world_gif.setObjectName("world_gif")
            self.BG3_2 = QtWidgets.QLabel(self.centralwidget)
            self.BG3_2.setGeometry(QtCore.QRect(940, 10, 421, 251))
            self.BG3_2.setStyleSheet("background-color: rgb(0, 255, 255);")
            self.BG3_2.setText("")
            self.BG3_2.setObjectName("BG3_2")
            self.neueon_jpg = QtWidgets.QLabel(self.centralwidget)
            self.neueon_jpg.setGeometry(QtCore.QRect(430, 10, 471, 111))
            self.neueon_jpg.setText("")
            self.neueon_jpg.setPixmap(QtGui.QPixmap(self.config.LOGO_IMAGE_DIR))  #LOGO_IMAGE_DIR
            self.neueon_jpg.setScaledContents(True)
            self.neueon_jpg.setObjectName("neueon_jpg")
            self.round_gif = QtWidgets.QLabel(self.centralwidget)
            self.round_gif.setGeometry(QtCore.QRect(370, 110, 561, 391))
            self.round_gif.setText("")
            self.round_gif.setPixmap(QtGui.QPixmap(self.config.VOICE_GIF_DIR)) #VOICE_GIF_DIR
            self.round_gif.setScaledContents(True)
            self.round_gif.setObjectName("round_gif")
            self.BG3_3 = QtWidgets.QLabel(self.centralwidget)
            self.BG3_3.setGeometry(QtCore.QRect(20, 640, 351, 71))
            self.BG3_3.setStyleSheet("background-color: rgb(0, 255, 255);")
            self.BG3_3.setText("")
            self.BG3_3.setObjectName("BG3_3")
            self.loading_gif = QtWidgets.QLabel(self.centralwidget)
            self.loading_gif.setGeometry(QtCore.QRect(30, 650, 331, 51))
            self.loading_gif.setText("")
            self.loading_gif.setPixmap(QtGui.QPixmap(self.config.LOADING_GIF_DIR))  #LOADING_GIF_DIR
            self.loading_gif.setScaledContents(True)
            self.loading_gif.setObjectName("loading_gif")
            self.human_gif = QtWidgets.QLabel(self.centralwidget)
            self.human_gif.setGeometry(QtCore.QRect(950, 20, 401, 231))
            self.human_gif.setText("")
            self.human_gif.setPixmap(QtGui.QPixmap(self.config.HEALTH_GIF_DIR)) #HEALTH_GIF_DIR
            self.human_gif.setScaledContents(True)
            self.human_gif.setObjectName("human_gif")
            self.prg2_gif = QtWidgets.QLabel(self.centralwidget)
            self.prg2_gif.setGeometry(QtCore.QRect(450, 520, 451, 191))
            self.prg2_gif.setText("")
            self.prg2_gif.setPixmap(QtGui.QPixmap(self.config.CODE_MIDDLE_GIF_DIR))  #CODE_MIDDLE_GIF_DIR
            self.prg2_gif.setScaledContents(True)
            self.prg2_gif.setObjectName("prg2_gif")
            self.label_4 = QtWidgets.QLabel(self.centralwidget)
            self.label_4.setGeometry(QtCore.QRect(500, 470, 47, 13))
            self.label_4.setObjectName("label_4")
            self.text_time = QtWidgets.QTextBrowser(self.centralwidget)
            self.text_time.setGeometry(QtCore.QRect(980, 300, 351, 71))
            self.text_time.setStyleSheet("background-color: Transparent;\n"
    "border-radius:none;\n"
    "color:white;\n"
    "font-size:45px;")
            self.text_time.setObjectName("text_time")
            self.text_bg = QtWidgets.QLabel(self.centralwidget)
            self.text_bg.setGeometry(QtCore.QRect(910, 270, 481, 131))
            self.text_bg.setText("")
            self.text_bg.setPixmap(QtGui.QPixmap(self.config.FRAME_IMAGE_DIR))  #FRAME_IMAGE_DIR
            self.text_bg.setScaledContents(True)
            self.text_bg.setObjectName("text_bg")
            self.text_bg_2 = QtWidgets.QLabel(self.centralwidget)
            self.text_bg_2.setGeometry(QtCore.QRect(910, 420, 481, 131))
            self.text_bg_2.setText("")
            self.text_bg_2.setPixmap(QtGui.QPixmap(self.config.FRAME_IMAGE_DIR))  #FRAME_IMAGE_DIR
            self.text_bg_2.setScaledContents(True)
            self.text_bg_2.setObjectName("text_bg_2")
            self.text_date = QtWidgets.QTextBrowser(self.centralwidget)
            self.text_date.setGeometry(QtCore.QRect(980, 450, 351, 71))
            self.text_date.setStyleSheet("background-color: Transparent;\n"
    "border-radius:none;\n"
    "color:white;\n"
    "font-size:32px;")
            self.text_date.setObjectName("text_date")
            self.exitButton = QtWidgets.QPushButton(self.centralwidget)
            self.exitButton.setGeometry(QtCore.QRect(1160, 630, 131, 61))
            self.exitButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
    "font: 24pt \"MS Shell Dlg 2\";")
            self.exitButton.setObjectName("exitButton")
            self.startButton_ = QtWidgets.QPushButton(self.centralwidget)
            self.startButton_.setGeometry(QtCore.QRect(990, 630, 131, 61))
            self.startButton_.setStyleSheet("\n"
    "font: 24pt \"MS Shell Dlg 2\";\n"
    "background-color: rgb(85, 255, 0);")
            self.startButton_.setObjectName("startButton_")
            self.BG1.raise_()
            self.initializing_gif.raise_()
            self.BG3_2.raise_()
            self.round_gif.raise_()
            self.BG3_3.raise_()
            self.loading_gif.raise_()
            self.human_gif.raise_()
            self.label_4.raise_()
            self.neueon_jpg.raise_()
            self.text_bg.raise_()
            self.text_time.raise_()
            self.text_bg_2.raise_()
            self.prg2_gif.raise_()
            self.text_date.raise_()
            self.prog_gif.raise_()
            self.world_gif.raise_()
            self.exitButton.raise_()
            self.startButton_.raise_()
            iNeuronDesktopAssistant.setCentralWidget(self.centralwidget)

            self.retranslateUi(iNeuronDesktopAssistant)
            QtCore.QMetaObject.connectSlotsByName(iNeuronDesktopAssistant)
        
        except Exception as e:
            gui_exception = GUIException(
                "Failed during setting up GUI configuration in module [{0}] class [{1}] method [{2}]"
                    .format(self.__module__, Ui_iNeuronDesktopAssistant.__name__,
                            self.setupUi.__name__))
            raise Exception(gui_exception.error_message_detail(str(e), sys)) from e


    def retranslateUi(self, iNeuronDesktopAssistant):
        try:
            _translate = QtCore.QCoreApplication.translate
            iNeuronDesktopAssistant.setWindowTitle(_translate("iNeuronDesktopAssistant", "Neuron Desktop Assistant"))
            self.label_4.setText(_translate("iNeuronDesktopAssistant", "TextLabel"))
            self.exitButton.setText(_translate("iNeuronDesktopAssistant", "EXIT"))
            self.startButton_.setText(_translate("iNeuronDesktopAssistant", "START"))
        
        except Exception as e:
            gui_exception = GUIException(
                "Failed during retranslate GUI in module [{0}] class [{1}] method [{2}]"
                    .format(self.__module__, Ui_iNeuronDesktopAssistant.__name__,
                            self.retranslateUi.__name__))
            raise Exception(gui_exception.error_message_detail(str(e), sys)) from e


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    iNeuronDesktopAssistant = QtWidgets.QMainWindow()
    ui = Ui_iNeuronDesktopAssistant()
    ui.setupUi(iNeuronDesktopAssistant)
    iNeuronDesktopAssistant.show()
    sys.exit(app.exec_())
